version: "3.8"
services:
#Banco de dados desativado, pois estou usando o Supabase
#  db:
#    image: postgres:16
#    container_name: twenty-postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -d postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#    restart: always

  redis:
    image: redis:7
    container_name: twenty-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-data:
